"""Regenerate ``src/noentenc/language_detection/_iso639.py`` from the SIL ISO 639-3 code tables,
and the list of every ISO 639-3 code the tests check labels against.

Usage: ``uv run python scripts/build_iso639_tables.py``
"""

import csv
import io
import urllib.request
from pathlib import Path

SIL = "https://iso639-3.sil.org/sites/iso639-3/files/downloads"
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/noentenc/language_detection/_iso639.py"
CODES_FIXTURE = ROOT / "tests/unit/language_detection/fixtures/iso639_3.txt"


def _fetch_tab(name: str) -> list[dict[str, str]]:
    request = urllib.request.Request(
        f"{SIL}/{name}", headers={"User-Agent": "noentenc"}
    )
    with urllib.request.urlopen(request) as response:  # noqa: S310 - fixed https URL
        text = response.read().decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text), delimiter="\t"))


def _format_dict(name: str, mapping: dict[str, str]) -> str:
    items = ", ".join(f'"{k}": "{v}"' for k, v in sorted(mapping.items()))
    return f"{name}: dict[str, str] = {{{items}}}\n"


def main() -> None:
    codes = _fetch_tab("iso-639-3.tab")
    macros = _fetch_tab("iso-639-3-macrolanguages.tab")
    retirements = _fetch_tab("iso-639-3_Retirements.tab")

    part1 = {row["Part1"]: row["Id"] for row in codes if row["Part1"]}
    macro = {row["I_Id"]: row["M_Id"] for row in macros if row["I_Status"] == "A"}
    retired = {row["Id"]: row["Change_To"] for row in retirements if row["Change_To"]}

    OUT.write_text(
        '"""ISO 639 lookup tables. Generated by ``scripts/build_iso639_tables.py``; do not edit."""\n\n'
        + _format_dict("PART1_TO_PART3", part1)
        + "\n"
        + _format_dict("INDIVIDUAL_TO_MACRO", macro)
        + "\n"
        + _format_dict("RETIRED_TO_CURRENT", retired),
        encoding="utf-8",
    )
    CODES_FIXTURE.write_text(
        "".join(f"{code}\n" for code in sorted(row["Id"] for row in codes)),
        encoding="utf-8",
    )
    print(f"wrote {OUT} and {CODES_FIXTURE}")


if __name__ == "__main__":
    main()
