"""Regenerate `src/noentenc/_catalog.py`: file sizes and licences of every pinned model.

`Translator.plan`, `LanguageDetector.plan` and the licence and download-size constraints
read the catalog, so they work offline and without downloading weights. Run it after
changing a pinned revision or adding a model:

    uv run python scripts/build_model_catalog.py

Sizes come from the Hugging Face API at each pinned revision (or an HTTP HEAD request
for files hosted elsewhere). Opus-MT licences come from the model cards of the
Helsinki-NLP models the Xenova exports were converted from.
"""

import json
import urllib.request
from pathlib import Path
from pprint import pformat

from huggingface_hub import HfApi

from noentenc.language_detection.models.fasttext.model import PRESETS as FASTTEXT
from noentenc.language_detection.models.langid_model import LANGID_SDIST
from noentenc.language_detection.models.onnx_classifier import (
    PRESETS as ONNX,
)
from noentenc.language_detection.models.onnx_classifier import (
    OnnxClassifierModel,
)
from noentenc.translation.models.m2m100 import M2M100Model
from noentenc.translation.models.nllb import NLLBModel
from noentenc.translation.models.opus_mt import OPUS_MT_REVISIONS, OpusMTModel
from noentenc.translation.models.small100 import SMaLL100Model

OUTPUT = Path(__file__).parents[1] / "src" / "noentenc" / "_catalog.py"
_HF_RESOLVE = "https://huggingface.co/"
_SPDX = {"cc-by-4.0": "CC-BY-4.0", "apache-2.0": "Apache-2.0", "mit": "MIT"}


def _repo_files(
    api: HfApi, repo: str, revision: str, files: list[str]
) -> dict[str, int]:
    infos = api.get_paths_info(repo, files, revision=revision)
    sizes = {info.path: info.size for info in infos}
    missing = sorted(set(files) - set(sizes))
    if missing:
        raise SystemExit(f"{repo}@{revision} has no {missing}")
    return sizes


def _head_size(url: str) -> int:
    request = urllib.request.Request(
        url, method="HEAD", headers={"User-Agent": "noentenc"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310 - fixed URLs
        return int(response.headers["Content-Length"])


def _remote_size(api: HfApi, url: str) -> int:
    if url.startswith(_HF_RESOLVE):
        repo_and_path = url.removeprefix(_HF_RESOLVE)
        owner, name, _resolve, revision, path = repo_and_path.split("/", 4)
        return _repo_files(api, f"{owner}/{name}", revision, [path])[path]
    return _head_size(url)


def translation(api: HfApi) -> tuple[dict[str, dict[str, int]], dict[str, str]]:
    sizes: dict[str, dict[str, int]] = {}
    licences: dict[str, str] = {}
    every_precision = lambda cls: sorted(  # noqa: E731
        {name for precision in cls.onnx_files for name in cls.filenames(precision)}
    )
    for cls in (SMaLL100Model, M2M100Model, NLLBModel):
        sizes[f"{cls.default_model}@{cls.default_revision}"] = _repo_files(
            api, cls.default_model, cls.default_revision, every_precision(cls)
        )
    for (source, target), revision in sorted(OPUS_MT_REVISIONS.items()):
        repo = f"Xenova/opus-mt-{source}-{target}"
        sizes[f"{repo}@{revision}"] = _repo_files(
            api, repo, revision, every_precision(OpusMTModel)
        )
        card = api.model_info(f"Helsinki-NLP/opus-mt-{source}-{target}").card_data
        licence = card.license if card else None
        if not licence:
            raise SystemExit(f"Helsinki-NLP/opus-mt-{source}-{target} names no licence")
        licences[repo] = _SPDX.get(str(licence).lower(), str(licence))
        print(repo, licences[repo], flush=True)
    return sizes, licences


def detection(api: HfApi) -> dict[str, int]:
    remotes = [preset.remote for preset in FASTTEXT.values()]
    remotes += [r for name in ONNX for r in OnnxClassifierModel.remote_files(name)]
    remotes.append(LANGID_SDIST)
    return {remote.cache_path: _remote_size(api, remote.url) for remote in remotes}


def main() -> None:
    api = HfApi()
    sizes, licences = translation(api)
    detection_sizes = detection(api)
    OUTPUT.write_text(
        '"""File sizes and licences of the pinned models. Generated by\n'
        'scripts/build_model_catalog.py; do not edit by hand."""\n\n'
        "# Bytes of each file, per `repo@revision`, for every precision.\n"
        f"TRANSLATION_FILE_SIZES: dict[str, dict[str, int]] = {pformat(sizes, width=88)}\n\n"
        "# SPDX licence of each Opus-MT pair, from its Helsinki-NLP model card.\n"
        f"OPUS_MT_LICENSES: dict[str, str] = {pformat(licences, width=88)}\n\n"
        "# Bytes of each detection file, by its cache path.\n"
        f"DETECTION_FILE_SIZES: dict[str, int] = {pformat(detection_sizes, width=88)}\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {"translation repos": len(sizes), "detection files": len(detection_sizes)}
        )
    )


if __name__ == "__main__":
    main()
