"""Regenerate ``src/noentenc/language_detection/_iso639.py`` from the SIL ISO 639-3 code tables.

Usage: ``uv run python scripts/build_iso639_tables.py``
"""

import csv
import io
import urllib.request
from pathlib import Path

SIL = "https://iso639-3.sil.org/sites/iso639-3/files/downloads"
OUT = Path(__file__).resolve().parents[1] / "src/noentenc/language_detection/_iso639.py"


def _fetch_tab(name: str) -> list[dict[str, str]]:
    request = urllib.request.Request(
        f"{SIL}/{name}", headers={"User-Agent": "noentenc"}
    )
    with urllib.request.urlopen(request) as response:  # noqa: S310 - fixed https URL
        text = response.read().decode("utf-8-sig")
    return list(csv.DictReader(io.StringIO(text), delimiter="\t"))


def _format_dict(name: str, mapping: dict[str, str]) -> str:
    items = ", ".join(f'"{k}": "{v}"' for k, v in sorted(mapping.items()))
    return f"{name}: dict[str, str] = {{{items}}}\n"


def main() -> None:
    codes = _fetch_tab("iso-639-3.tab")
    macros = _fetch_tab("iso-639-3-macrolanguages.tab")
    retirements = _fetch_tab("iso-639-3_Retirements.tab")

    part1 = {row["Part1"]: row["Id"] for row in codes if row["Part1"]}
    macro = {row["I_Id"]: row["M_Id"] for row in macros if row["I_Status"] == "A"}
    retired = {row["Id"]: row["Change_To"] for row in retirements if row["Change_To"]}
    valid = " ".join(sorted(row["Id"] for row in codes))

    OUT.write_text(
        '"""ISO 639 lookup tables. Generated by ``scripts/build_iso639_tables.py``; do not edit."""\n\n'
        + _format_dict("PART1_TO_PART3", part1)
        + "\n"
        + _format_dict("INDIVIDUAL_TO_MACRO", macro)
        + "\n"
        + _format_dict("RETIRED_TO_CURRENT", retired)
        + "\n"
        + f'VALID_PART3: str = "{valid}"\n',
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
